### ISSUE TITLE
Fix formating issues

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/data-exchange-agreements#1]
@georgepadayatti I can take care of this change as its easy

**Comment by georgepadayatti** [comment]
Thanks @lalc. 

In case you want to refer a specific portion of the spec, you can actually do that using GitHub permalinks. For e.g. I have referred Lines 34 - 42 below.

https://github.com/decentralised-dataexchange/data-exchange-agreements/blob/8324534223edbdf0ae91a6dfc1b6526d1a9a16e5/docs/protocol/datadisclosure-agreement-protocol-specification.md?plain=1#L34-L42

**Comment by georgepadayatti** [comment]
The above is done using the menu shown in the image below.

<img width="1279" alt="Screenshot 2022-06-09 at 9 56 28 PM" src="https://user-images.githubusercontent.com/16397960/172897227-8afb29ed-daa4-4b1a-9c68-ebaed5fd8856.png">

**Comment by lalc** [comment]
Made formatting changes along with taking care of all review comments
