### ISSUE TITLE
incorrect links

### ISSUE THREAD

**Issue by JanLin** [decentralised-dataexchange/data-exchange-agreements#2]
Small issue. Two links are incorrect.
https://didcomm.org/mydata-did/2.0 leads nowhere
and
[Data Disclosure Agreement (DDA)](https://github.com/decentralised-dataexchange/data-exchange-agreements/blob/main/interface-specs/data-disclosure-agreement-schema/data-disclosure-agreement-schema-context.jsonld)

correct one
https://github.com/decentralised-dataexchange/data-exchange-agreements/blob/main/interface-specs/jsonld/contexts/dexa-context.jsonld

**Comment by lalc** [comment]
Which are the effected files @JanLin?

**Comment by JanLin** [comment]
Sorry, missed to point at section. This is where didcomm was incorrect. And next section "create" has incorrect DDA link.

https://github.com/decentralised-dataexchange/data-exchange-agreements/blob/main/docs/did/spec.md#operations

**Comment by lalc** [comment]
Fixed. Pls, note that https://didcomm.org/mydata-did/2.0 is not an URL but a DIDComm v1 message type prefix.
